apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: app-maven-kaniko1
  annotations:
    ootb.apps.tanzu.vmware.com/servicebinding-workload: "true"
    ootb.apps.tanzu.vmware.com/apidescriptor-ref: "true"
    kapp.k14s.io/change-rule: upsert after upserting servicebinding.io/ServiceBindings
  labels:
    app.kubernetes.io/part-of: app-maven-kaniko1
    apps.tanzu.vmware.com/has-tests: "true"
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/component: run
    carto.run/workload-name: app-maven-kaniko1
spec:
  template:
    metadata:
      annotations:
        conventions.carto.run/applied-conventions: |-
          appliveview-sample/app-live-view-appflavour-check
          spring-boot-convention/auto-configure-actuators-check
          spring-boot-convention/app-live-view-appflavour-check
        developer.conventions/target-containers: workload
      labels:
        app.kubernetes.io/component: run
        app.kubernetes.io/part-of: app-maven-kaniko1
        apps.tanzu.vmware.com/has-tests: "true"
        apps.tanzu.vmware.com/workload-type: web
        carto.run/workload-name: app-maven-kaniko1
    spec:
      containers:
      - image: gcr.io/ship-interfaces-dev/supply-chain/app-maven-kaniko1-dev@sha256:644148c2bbee25088634d819a49bcde98ce15d5f3ab885d7ad566f80399d56a5
        name: workload
        resources: {}
        securityContext:
          runAsUser: 1000
      serviceAccountName: default

