apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: simple-conventions
  annotations:
    ootb.apps.tanzu.vmware.com/servicebinding-workload: "true"
    ootb.apps.tanzu.vmware.com/apidescriptor-ref: "true"
    kapp.k14s.io/change-rule: upsert after upserting servicebinding.io/ServiceBindings
  labels:
    app.kubernetes.io/part-of: simple-conventions
    apps.tanzu.vmware.com/has-tests: "true"
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/component: run
    carto.run/workload-name: simple-conventions
spec:
  template:
    metadata:
      annotations:
        conventions.carto.run/applied-conventions: |-
          appliveview-sample/app-live-view-appflavour-check
          spring-boot-convention/auto-configure-actuators-check
          spring-boot-convention/app-live-view-appflavour-check
        developer.conventions/target-containers: workload
      labels:
        app.kubernetes.io/component: run
        app.kubernetes.io/part-of: simple-conventions
        apps.tanzu.vmware.com/has-tests: "true"
        apps.tanzu.vmware.com/workload-type: web
        carto.run/workload-name: simple-conventions
    spec:
      containers:
      - image: gcr.io/ship-interfaces-dev/supply-chain/simple-conventions-dev@sha256:a4a1f47101eeec45dceaba1889efc8640dc77f24918ccb296136a2ab43432d99
        name: workload
        resources: {}
        securityContext:
          runAsUser: 1000
      serviceAccountName: default

