apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: bwced
  annotations:
    ootb.apps.tanzu.vmware.com/servicebinding-workload: "true"
    ootb.apps.tanzu.vmware.com/apidescriptor-ref: "true"
    kapp.k14s.io/change-rule: upsert after upserting servicebinding.io/ServiceBindings
  labels:
    app.kubernetes.io/part-of: bwced
    apps.tanzu.vmware.com/has-tests: "true"
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/component: run
    carto.run/workload-name: bwced
spec:
  template:
    metadata:
      annotations:
        conventions.carto.run/applied-conventions: |-
          appliveview-sample/app-live-view-appflavour-check
          simple-convention/garethjevans.org-carto-run-workload-name
          simple-convention/garethjevans.org-args
          simple-convention/garethjevans.org-storage
          spring-boot-convention/auto-configure-actuators-check
          spring-boot-convention/app-live-view-appflavour-check
        developer.conventions/target-containers: workload
        garethjevans.org/args: '["run","--bind-address","0.0.0.0","--document-root","/storage"]'
        garethjevans.org/storage: '{"volumeMounts":[{"mountPath":"/storage","name":"storage"}],"volumes":[{"name":"storage","emptyDir":{}}]}'
      labels:
        app.kubernetes.io/component: run
        app.kubernetes.io/part-of: bwced
        apps.tanzu.vmware.com/has-tests: "true"
        apps.tanzu.vmware.com/workload-type: web
        carto.run/workload-name: bwced
    spec:
      containers:
      - args:
        - run
        - --bind-address
        - 0.0.0.0
        - --document-root
        - /storage
        env:
        - name: CARTO_RUN_WORKLOAD_NAME
          value: bwced
        image: gcr.io/ship-interfaces-dev/supply-chain/bwced-dev@sha256:346c53cde224db2f0875cc0015b87bf93b23914d57e34b3888822a731b311088
        name: workload
        resources: {}
        securityContext:
          runAsUser: 1000
        volumeMounts:
        - mountPath: /storage
          name: storage
      serviceAccountName: default
      volumes:
      - emptyDir: {}
        name: storage

