apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: app-golang-kaniko-test
  annotations:
    ootb.apps.tanzu.vmware.com/servicebinding-workload: "true"
    ootb.apps.tanzu.vmware.com/apidescriptor-ref: "true"
    kapp.k14s.io/change-rule: upsert after upserting servicebinding.io/ServiceBindings
  labels:
    app.kubernetes.io/part-of: app-golang-kaniko-test
    apps.tanzu.vmware.com/has-tests: "true"
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/component: run
    carto.run/workload-name: app-golang-kaniko-test
spec:
  template:
    metadata:
      annotations:
        conventions.carto.run/applied-conventions: |-
          appliveview-sample/app-live-view-appflavour-check
          simple-convention/garethjevans.org-carto-run-workload-name
          spring-boot-convention/auto-configure-actuators-check
          spring-boot-convention/app-live-view-appflavour-check
        developer.conventions/target-containers: workload
      labels:
        app.kubernetes.io/component: run
        app.kubernetes.io/part-of: app-golang-kaniko-test
        apps.tanzu.vmware.com/has-tests: "true"
        apps.tanzu.vmware.com/workload-type: web
        carto.run/workload-name: app-golang-kaniko-test
    spec:
      containers:
      - env:
        - name: CARTO_RUN_WORKLOAD_NAME
          value: app-golang-kaniko-test
        image: gcr.io/ship-interfaces-dev/supply-chain/app-golang-kaniko-test-dev@sha256:a3e5db4e666e532e89fa3dcb1f280b99e9dde6e597987685ae37a9ae0e0ee148
        name: workload
        resources: {}
        securityContext:
          runAsUser: 1000
      serviceAccountName: default

